baseurl: "/"
languageCode: "en-us"
title: "Elise Li Zheng"
theme: "hugo-xmin"
googleAnalytics: ""
disqusShortname: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
footnotereturnlinkcontents: "↩"

permalinks:
  note: "/note/:year/:month/:day/:slug/"
  post: "/post/:year/:month/:day/:slug/"

menu:
  main:
    - name: Home
      url: ""
      weight: 1
    - name: 中文
      url: "chinese/"
      weight: 2
    - name: Post
      url: "post/"
      weight: 3
    - name: Tags
      url: "tags/"
      weight: 4
    - name: Subscribe
      url: "index.xml"

params:
  description: "A personal website for Elise Li Zheng."
  footer: "&copy; [Elise Li Zheng](https://elise901.com)  2021 | [Research Gate](https://www.researchgate.net/profile/Elise-Zheng) | [Twitter](https://twitter.com/elise901) | [Instagram](https://www.instagram.com/eliselizi/)"

markup:
  highlight:
    codeFences: false
  goldmark:
    renderer:
      unsafe: true
